name: flutter_bloc_tutorial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  dartz: ^0.10.0
  dio: ^4.0.4
  fast_immutable_collections: ^7.0.3
  flutter:
    sdk: flutter
  firebase_core: ^1.10.2
  firebase_crashlytics: ^2.4.0
  flutter_bloc: ^8.0.0
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1


flutter:
  uses-material-design: true
